/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaMV;

import Controlador.ControlFactura;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author kathy
 */
public class Facturacion extends javax.swing.JDialog {

    public static String s;
    public static String i;
    ArrayList<TablaProducto> productos;

    /**
     * Creates new form F
     */
    

    public Facturacion() {
    }

    public Facturacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.tfCantidad.setEditable(false);
        this.tfCantidad.setText("");
        this.btnAgregarProducto.setActionCommand("agregarProducto");
        this.btnCerrarFd.setActionCommand("cerrarF");
        this.btnEliminarFila.setActionCommand("eliminarFila");
        this.btnVender.setActionCommand("vender");
        this.cbProducto.setActionCommand("cbProducto");
        this.cbVendedor.setActionCommand("cbVendedor");
        this.btnPrecargar.setActionCommand("Precargar");
        this.btnCantidad.setActionCommand("ModificarCantidad");
        
        this.setLocationRelativeTo(null);
        s ="s";
        i = "i";
        rSDateFecha.setDatoFecha(new Date());
    }
    
     public void setControl(ControlFactura control){
        this.btnCerrarFd.addActionListener(control);
        this.miTb1.addMouseListener(control);
        this.btnAgregarProducto.addActionListener(control);
        this.btnEliminarFila.addActionListener(control);
        this.btnVender.addActionListener(control);
        this.cbProducto.addActionListener(control);
        this.cbVendedor.addActionListener(control);
        this.btnPrecargar.addActionListener(control);
        this.btnCantidad.addActionListener(control);
        //this.lbNomPr.addMouseListener(control);
//        this.jpEscritorioF.addMouseListener(control);/////////
//        this.tfCliente.addMouseListener(control);////////////
    }
    
    public void iniciar(){
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpEscritorioF = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNFactura = new javax.swing.JTextField();
        tfCliente = new javax.swing.JTextField();
        cbProducto = new javax.swing.JComboBox<>();
        tfCantidad = new javax.swing.JTextField();
        jLabelNumerito = new javax.swing.JLabel();
        jLabelCliente = new javax.swing.JLabel();
        jLabelCanti = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbVendedor = new javax.swing.JComboBox<>();
        jLabelVendedor = new javax.swing.JLabel();
        tfDireccion = new javax.swing.JTextField();
        tfPrecioUni = new javax.swing.JTextField();
        jLabelPreUni = new javax.swing.JLabel();
        tfPrecioTotalProducto = new javax.swing.JTextField();
        jLabelPreciTotal = new javax.swing.JLabel();
        btnCerrarFd = new principal.MaterialButtonCircle();
        jLabel10 = new javax.swing.JLabel();
        rSDateFecha = new rojeru_san.componentes.RSDateChooser();
        btnAgregarProducto = new rojeru_san.complementos.RSButtonHover();
        jLabel12 = new javax.swing.JLabel();
        tfTotalPagar = new javax.swing.JTextField();
        jLabelTotal = new javax.swing.JLabel();
        btnEliminarFila = new rojeru_san.complementos.RSButtonHover();
        btnVender = new rojeru_san.complementos.RSButtonHover();
        jScrollPane2 = new javax.swing.JScrollPane();
        miTb1 = new javax.swing.JTable();
        btnPrecargar = new javax.swing.JButton();
        btnCantidad = new javax.swing.JButton();
        lbNomPr = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfExistenciaProd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NOMBRE DE LA EMPRESA");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("N Factura:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cliente:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Producto:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Fecha:");

        tfNFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNFacturaActionPerformed(evt);
            }
        });
        tfNFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNFacturaKeyTyped(evt);
            }
        });

        tfCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfClienteKeyTyped(evt);
            }
        });

        cbProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Productos" }));

        tfCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCantidadActionPerformed(evt);
            }
        });
        tfCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCantidadKeyTyped(evt);
            }
        });

        jLabelNumerito.setForeground(new java.awt.Color(255, 51, 51));

        jLabelCliente.setForeground(new java.awt.Color(255, 0, 0));

        jLabelCanti.setForeground(new java.awt.Color(255, 0, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Vendedor:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Direccion:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Precio Unitario:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Precio Total:");

        cbVendedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Vendedor" }));

        jLabelVendedor.setForeground(new java.awt.Color(255, 0, 0));

        tfDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDireccionActionPerformed(evt);
            }
        });

        tfPrecioUni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPrecioUniKeyTyped(evt);
            }
        });

        jLabelPreUni.setForeground(new java.awt.Color(255, 0, 0));

        tfPrecioTotalProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPrecioTotalProductoKeyTyped(evt);
            }
        });

        jLabelPreciTotal.setForeground(new java.awt.Color(255, 0, 0));

        btnCerrarFd.setBackground(new java.awt.Color(220, 20, 20));
        btnCerrarFd.setText("X");
        btnCerrarFd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarFdActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Cantidad:");

        btnAgregarProducto.setText("Agregar al Carrito");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("TOTAL A PAGAR:");

        tfTotalPagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTotalPagarKeyTyped(evt);
            }
        });

        jLabelTotal.setForeground(new java.awt.Color(255, 0, 0));

        btnEliminarFila.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminarFila.setText("Eliminar");
        btnEliminarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFilaActionPerformed(evt);
            }
        });

        btnVender.setText("Vender");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        miTb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Cantidad", "Producto", "P/U", "Total"
            }
        ));
        jScrollPane2.setViewportView(miTb1);

        btnPrecargar.setText("Precargar");

        btnCantidad.setText("Modificar");

        lbNomPr.setText("lol");

        jLabel11.setText("Existencia:");

        tfExistenciaProd.setText("-----------------------------------");
        tfExistenciaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfExistenciaProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpEscritorioFLayout = new javax.swing.GroupLayout(jpEscritorioF);
        jpEscritorioF.setLayout(jpEscritorioFLayout);
        jpEscritorioFLayout.setHorizontalGroup(
            jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEscritorioFLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpEscritorioFLayout.createSequentialGroup()
                        .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEscritorioFLayout.createSequentialGroup()
                                .addComponent(tfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpEscritorioFLayout.createSequentialGroup()
                                .addComponent(cbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSDateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(jpEscritorioFLayout.createSequentialGroup()
                        .addComponent(tfNFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNumerito, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbNomPr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpEscritorioFLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPrecargar))
                    .addGroup(jpEscritorioFLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(tfPrecioTotalProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(jpEscritorioFLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPrecioUni, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEscritorioFLayout.createSequentialGroup()
                        .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfExistenciaProd)
                            .addComponent(tfCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                        .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEscritorioFLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabelCanti, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCantidad))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEscritorioFLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPreUni, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPreciTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpEscritorioFLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarFd, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpEscritorioFLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnEliminarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(jpEscritorioFLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1068, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEscritorioFLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(tfTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jpEscritorioFLayout.setVerticalGroup(
            jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEscritorioFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpEscritorioFLayout.createSequentialGroup()
                        .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCerrarFd, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfNFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelNumerito, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(cbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPrecargar)
                        .addComponent(lbNomPr)))
                .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEscritorioFLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(tfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpEscritorioFLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addComponent(jLabelCanti, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCantidad))
                        .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpEscritorioFLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabelPreUni, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEscritorioFLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfExistenciaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))))))
                .addGap(18, 18, 18)
                .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPreciTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfPrecioUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEscritorioFLayout.createSequentialGroup()
                        .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSDateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(tfTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminarFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpEscritorioFLayout.createSequentialGroup()
                        .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPrecioTotalProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEscritorioF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEscritorioF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNFacturaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfNFacturaActionPerformed

    private void tfNFacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNFacturaKeyTyped
        // TODO add your handling code here:
        this.tfNFactura.setEditable(false);
        char vali = evt.getKeyChar();
        if (Character.isDigit(vali)) {
            evt.consume();
            jLabelNumerito.setText("Este campo no es editable");
        } else {
            jLabelNumerito.setText("Este campo no es editable");
        }
    }//GEN-LAST:event_tfNFacturaKeyTyped

    private void tfClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfClienteKeyTyped
        // TODO add your handling code here:
        char vali = evt.getKeyChar();
        if (Character.isDigit(vali)) {
            evt.consume();
            jLabelCliente.setText("Digitar letras");
        } else {
            jLabelCliente.setText("");
        }
    }//GEN-LAST:event_tfClienteKeyTyped

    private void tfCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCantidadKeyTyped
        // TODO add your handling code here:
        char vali = evt.getKeyChar();
        if (Character.isDigit(vali)) {
            jLabelCanti.setText("");
        } else {
            //JOptionPane.showMessageDialog(null, "Digitar Numeros");
            jLabelCanti.setText("Digitar numeros");
            evt.consume();
        }
    }//GEN-LAST:event_tfCantidadKeyTyped

    private void tfPrecioUniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrecioUniKeyTyped
        // TODO add your handling code here:
        this.tfPrecioUni.setEditable(false);
        char vali = evt.getKeyChar();
        if (Character.isDigit(vali)) {
            evt.consume();
            jLabelPreUni.setText("Este campo no es editable");
        } else {
            jLabelPreUni.setText("Este campo no es editable");
        }
    }//GEN-LAST:event_tfPrecioUniKeyTyped

    private void tfPrecioTotalProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrecioTotalProductoKeyTyped
        // TODO add your handling code here:
        this.tfPrecioTotalProducto.setEditable(false);
        char vali = evt.getKeyChar();
        if (Character.isDigit(vali)) {
            evt.consume();
            jLabelPreciTotal.setText("Este campo no es editable");
        } else {
            jLabelPreciTotal.setText("Este campo no es editable");
        }
    }//GEN-LAST:event_tfPrecioTotalProductoKeyTyped

    private void btnCerrarFdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarFdActionPerformed
        // TODO add your handling code here:
        s = null;
        this.dispose();
    }//GEN-LAST:event_btnCerrarFdActionPerformed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
//        // TODO add your handling code here:
//        if(!tfCliente.getText().isEmpty()
//            && !tfDireccion.getText().isEmpty()
//            && !tfCantidad.getText().isEmpty()
//            //            && !rSDateFecha.getDatoFecha().isEmpty()
//
//        ){
//
//            //            Aqui voy hacer que se almacenen en la tabla
//
////            limpiarVista();
////
////        }else{
////            actualizar();
////            JOptionPane.showMessageDialog(null,"Llenar todos los Campos","ERROR",JOptionPane.ERROR_MESSAGE);
//        }
//
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void tfTotalPagarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTotalPagarKeyTyped
        // TODO add your handling code here:
//        this.tfPrecioUni.setEditable(false);
//        char vali = evt.getKeyChar();
//        if(Character.isDigit(vali)){
//            evt.consume();
//            jLabelTotal.setText("Este campo no es editable");
//        }else{
//            jLabelTotal.setText("Este campo no es editable");
//        }
    }//GEN-LAST:event_tfTotalPagarKeyTyped

    private void btnEliminarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFilaActionPerformed
        //        if(!existe()){
            //            if( !tfCodigo.getText().isEmpty()
                //                &&!tfDescrip.getText().isEmpty()
                //                &&!tfPrecio.getText().isEmpty()){
                //                double precio = Double.parseDouble(tfPrecio.getText());
                //                TablaProducto obj = new TablaProducto(tfCodigo.getText(),tfDescrip.getText(),precio);
                //                producto.add(obj);
                //                limpiar();
                //                mostrar();
                //
                //            }else{
                //                JOptionPane.showMessageDialog(null,"Campos Vacios","Error",JOptionPane.ERROR_MESSAGE);
                //            }
            //        }else{
            //            JOptionPane.showMessageDialog(null,"Codigo ya existe","Error",JOptionPane.ERROR_MESSAGE);
            //        }
    }//GEN-LAST:event_btnEliminarFilaActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnVenderActionPerformed

    private void tfDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDireccionActionPerformed

    private void tfCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCantidadActionPerformed

    private void tfExistenciaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfExistenciaProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfExistenciaProdActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Facturacion dialog = new Facturacion(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public rojeru_san.complementos.RSButtonHover btnAgregarProducto;
    public javax.swing.JButton btnCantidad;
    public principal.MaterialButtonCircle btnCerrarFd;
    public rojeru_san.complementos.RSButtonHover btnEliminarFila;
    public javax.swing.JButton btnPrecargar;
    public rojeru_san.complementos.RSButtonHover btnVender;
    public javax.swing.JComboBox<String> cbProducto;
    public javax.swing.JComboBox<String> cbVendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelCanti;
    public javax.swing.JLabel jLabelCliente;
    public javax.swing.JLabel jLabelNumerito;
    public javax.swing.JLabel jLabelPreUni;
    public javax.swing.JLabel jLabelPreciTotal;
    public javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelVendedor;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JPanel jpEscritorioF;
    public javax.swing.JLabel lbNomPr;
    public javax.swing.JTable miTb1;
    public rojeru_san.componentes.RSDateChooser rSDateFecha;
    public javax.swing.JTextField tfCantidad;
    public javax.swing.JTextField tfCliente;
    public javax.swing.JTextField tfDireccion;
    public javax.swing.JTextField tfExistenciaProd;
    public javax.swing.JTextField tfNFactura;
    public javax.swing.JTextField tfPrecioTotalProducto;
    public javax.swing.JTextField tfPrecioUni;
    public javax.swing.JTextField tfTotalPagar;
    // End of variables declaration//GEN-END:variables
}
