/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaMV;

import Controlador.ControlFactura;

import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author kathy
 */
public class FacturacionD extends javax.swing.JDialog {

    public static String s;
    public static String i;
    ArrayList<Producto> productos;

    /**
     * Creates new form F
     */
    
    
    public FacturacionD() {
    }

    public FacturacionD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.btnCar.setActionCommand("carrito");
        this.btnCerrarFd.setActionCommand("x");
        this.btnSalirF.setActionCommand("salirF");
        this.btnVenderF.setActionCommand("venderF");
        
        this.setLocationRelativeTo(null);
        s ="s";
        i = "i";
        rSDateFecha.setDatoFecha(new Date());
    }
    
     public void setControl(ControlFactura control){
        this.btnCerrarFd.addActionListener(control);
        this.miTb.addMouseListener(control);
        this.btnCar.addActionListener(control);
        this.btnSalirF.addActionListener(control);
        this.btnVenderF.addActionListener(control);
    }
    
    public void iniciar(){
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        miTb = new javax.swing.JTable();
        btnVenderF = new rojeru_san.complementos.RSButtonHover();
        jpEscritorioF = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextNume = new javax.swing.JTextField();
        jTextCliente = new javax.swing.JTextField();
        jCoBoxProduct = new javax.swing.JComboBox<>();
        jTextCanti = new javax.swing.JTextField();
        jLabelNumerito = new javax.swing.JLabel();
        jLabelCliente = new javax.swing.JLabel();
        jLabelProduc = new javax.swing.JLabel();
        jLabelCanti = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCoBoxVended = new javax.swing.JComboBox<>();
        jLabelVendedor = new javax.swing.JLabel();
        jTextDirec = new javax.swing.JTextField();
        jTextPreciUnit = new javax.swing.JTextField();
        jLabelPreUni = new javax.swing.JLabel();
        jTextPreciTo = new javax.swing.JTextField();
        jLabelPreciTotal = new javax.swing.JLabel();
        btnCerrarFd = new principal.MaterialButtonCircle();
        jLabel10 = new javax.swing.JLabel();
        rSDateFecha = new rojeru_san.componentes.RSDateChooser();
        btnCar = new rojeru_san.complementos.RSButtonHover();
        jLabel12 = new javax.swing.JLabel();
        jTextTotal = new javax.swing.JTextField();
        jLabelTotal = new javax.swing.JLabel();
        btnSalirF = new rojeru_san.complementos.RSButtonHover();
        btnVenderF1 = new rojeru_san.complementos.RSButtonHover();
        jScrollPane2 = new javax.swing.JScrollPane();
        miTb1 = new javax.swing.JTable();

        miTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Cantidad", "Producto", "P/U", "Total"
            }
        ));
        jScrollPane1.setViewportView(miTb);

        btnVenderF.setText("Vender");
        btnVenderF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderFActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NOMBRE DE LA EMPRESA");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("N Factura:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cliente:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Producto:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Fecha:");

        jTextNume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumeActionPerformed(evt);
            }
        });
        jTextNume.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNumeKeyTyped(evt);
            }
        });

        jTextCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextClienteKeyTyped(evt);
            }
        });

        jCoBoxProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Productos" }));

        jTextCanti.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCantiKeyTyped(evt);
            }
        });

        jLabelNumerito.setForeground(new java.awt.Color(255, 51, 51));

        jLabelCliente.setForeground(new java.awt.Color(255, 0, 0));

        jLabelProduc.setForeground(new java.awt.Color(255, 0, 0));

        jLabelCanti.setForeground(new java.awt.Color(255, 0, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Vendedor:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Direccion:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Precio Unitario:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Precio Total:");

        jCoBoxVended.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Vendedor" }));

        jLabelVendedor.setForeground(new java.awt.Color(255, 0, 0));

        jTextPreciUnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPreciUnitKeyTyped(evt);
            }
        });

        jLabelPreUni.setForeground(new java.awt.Color(255, 0, 0));

        jTextPreciTo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPreciToKeyTyped(evt);
            }
        });

        jLabelPreciTotal.setForeground(new java.awt.Color(255, 0, 0));

        btnCerrarFd.setBackground(new java.awt.Color(220, 20, 20));
        btnCerrarFd.setText("X");
        btnCerrarFd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarFdActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Cantidad:");

        btnCar.setText("Agregar al Carrito");
        btnCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("TOTAL A PAGAR:");

        jTextTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextTotalKeyTyped(evt);
            }
        });

        jLabelTotal.setForeground(new java.awt.Color(255, 0, 0));

        btnSalirF.setBackground(new java.awt.Color(255, 51, 51));
        btnSalirF.setText("Salir");
        btnSalirF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirFActionPerformed(evt);
            }
        });

        btnVenderF1.setText("Vender");
        btnVenderF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderF1ActionPerformed(evt);
            }
        });

        miTb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Cantidad", "Producto", "P/U", "Total"
            }
        ));
        jScrollPane2.setViewportView(miTb1);

        javax.swing.GroupLayout jpEscritorioFLayout = new javax.swing.GroupLayout(jpEscritorioF);
        jpEscritorioF.setLayout(jpEscritorioFLayout);
        jpEscritorioFLayout.setHorizontalGroup(
            jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEscritorioFLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEscritorioFLayout.createSequentialGroup()
                        .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpEscritorioFLayout.createSequentialGroup()
                                .addComponent(jTextNume, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelNumerito, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpEscritorioFLayout.createSequentialGroup()
                                .addComponent(jTextCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpEscritorioFLayout.createSequentialGroup()
                                .addComponent(jCoBoxProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelProduc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jpEscritorioFLayout.createSequentialGroup()
                                .addComponent(jTextCanti, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCanti, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46)
                        .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jpEscritorioFLayout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCoBoxVended, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jpEscritorioFLayout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextDirec, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpEscritorioFLayout.createSequentialGroup()
                                .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jpEscritorioFLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextPreciTo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpEscritorioFLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextPreciUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPreUni, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPreciTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpEscritorioFLayout.createSequentialGroup()
                        .addComponent(rSDateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))))
            .addGroup(jpEscritorioFLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarFd, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEscritorioFLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jTextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jpEscritorioFLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnSalirF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVenderF1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(jpEscritorioFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1068, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpEscritorioFLayout.setVerticalGroup(
            jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEscritorioFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpEscritorioFLayout.createSequentialGroup()
                        .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpEscritorioFLayout.createSequentialGroup()
                                .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCerrarFd, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelNumerito, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCoBoxVended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(8, 8, 8)
                        .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jTextCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextDirec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEscritorioFLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jCoBoxProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpEscritorioFLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelPreUni, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextPreciUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLabelProduc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextCanti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addComponent(jLabelCanti, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextPreciTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelPreciTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSDateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jTextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jpEscritorioFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalirF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVenderF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEscritorioF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEscritorioF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextNumeActionPerformed

    private void jTextNumeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNumeKeyTyped
        // TODO add your handling code here:
        this.jTextNume.setEditable(false);
        char vali = evt.getKeyChar();
        if (Character.isDigit(vali)) {
            evt.consume();
            jLabelNumerito.setText("Este campo no es editable");
        } else {
            jLabelNumerito.setText("Este campo no es editable");
        }
    }//GEN-LAST:event_jTextNumeKeyTyped

    private void jTextClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextClienteKeyTyped
        // TODO add your handling code here:
        char vali = evt.getKeyChar();
        if (Character.isDigit(vali)) {
            evt.consume();
            jLabelCliente.setText("Digitar letras");
        } else {
            jLabelCliente.setText("");
        }
    }//GEN-LAST:event_jTextClienteKeyTyped

    private void jTextCantiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCantiKeyTyped
        // TODO add your handling code here:
        char vali = evt.getKeyChar();
        if (Character.isDigit(vali)) {
            jLabelCanti.setText("");
        } else {
            jLabelCanti.setText("Digitar numeros");
            evt.consume();
        }
    }//GEN-LAST:event_jTextCantiKeyTyped

    private void jTextPreciUnitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPreciUnitKeyTyped
        // TODO add your handling code here:
        this.jTextPreciUnit.setEditable(false);
        char vali = evt.getKeyChar();
        if (Character.isDigit(vali)) {
            evt.consume();
            jLabelPreUni.setText("Este campo no es editable");
        } else {
            jLabelPreUni.setText("Este campo no es editable");
        }
    }//GEN-LAST:event_jTextPreciUnitKeyTyped

    private void jTextPreciToKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPreciToKeyTyped
        // TODO add your handling code here:
        this.jTextPreciTo.setEditable(false);
        char vali = evt.getKeyChar();
        if (Character.isDigit(vali)) {
            evt.consume();
            jLabelPreciTotal.setText("Este campo no es editable");
        } else {
            jLabelPreciTotal.setText("Este campo no es editable");
        }
    }//GEN-LAST:event_jTextPreciToKeyTyped

    private void btnCerrarFdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarFdActionPerformed
        // TODO add your handling code here:
        s = null;
        this.dispose();
    }//GEN-LAST:event_btnCerrarFdActionPerformed

    private void btnCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarActionPerformed
        // TODO add your handling code here:
        if(!jTextCliente.getText().isEmpty()
            && !jTextDirec.getText().isEmpty()
            && !jTextCanti.getText().isEmpty()
            //            && !rSDateFecha.getDatoFecha().isEmpty()

        ){

            //            Aqui voy hacer que se almacenen en la tabla

//            limpiarVista();
//
//        }else{
//            actualizar();
//            JOptionPane.showMessageDialog(null,"Llenar todos los Campos","ERROR",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnCarActionPerformed

    private void jTextTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTotalKeyTyped
        // TODO add your handling code here:
        this.jTextPreciUnit.setEditable(false);
        char vali = evt.getKeyChar();
        if(Character.isDigit(vali)){
            evt.consume();
            jLabelTotal.setText("Este campo no es editable");
        }else{
            jLabelTotal.setText("Este campo no es editable");
        }
    }//GEN-LAST:event_jTextTotalKeyTyped

    private void btnSalirFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirFActionPerformed
        //        if(!existe()){
            //            if( !tfCodigo.getText().isEmpty()
                //                &&!tfDescrip.getText().isEmpty()
                //                &&!tfPrecio.getText().isEmpty()){
                //                double precio = Double.parseDouble(tfPrecio.getText());
                //                Producto obj = new Producto(tfCodigo.getText(),tfDescrip.getText(),precio);
                //                producto.add(obj);
                //                limpiar();
                //                mostrar();
                //
                //            }else{
                //                JOptionPane.showMessageDialog(null,"Campos Vacios","Error",JOptionPane.ERROR_MESSAGE);
                //            }
            //        }else{
            //            JOptionPane.showMessageDialog(null,"Codigo ya existe","Error",JOptionPane.ERROR_MESSAGE);
            //        }
    }//GEN-LAST:event_btnSalirFActionPerformed

    private void btnVenderFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnVenderFActionPerformed

    private void btnVenderF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderF1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnVenderF1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FacturacionD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FacturacionD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FacturacionD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FacturacionD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FacturacionD dialog = new FacturacionD(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public rojeru_san.complementos.RSButtonHover btnCar;
    public principal.MaterialButtonCircle btnCerrarFd;
    public rojeru_san.complementos.RSButtonHover btnSalirF;
    public rojeru_san.complementos.RSButtonHover btnVenderF;
    public rojeru_san.complementos.RSButtonHover btnVenderF1;
    public javax.swing.JComboBox<String> jCoBoxProduct;
    public javax.swing.JComboBox<String> jCoBoxVended;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelCanti;
    public javax.swing.JLabel jLabelCliente;
    public javax.swing.JLabel jLabelNumerito;
    public javax.swing.JLabel jLabelPreUni;
    public javax.swing.JLabel jLabelPreciTotal;
    private javax.swing.JLabel jLabelProduc;
    public javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelVendedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField jTextCanti;
    public javax.swing.JTextField jTextCliente;
    public javax.swing.JTextField jTextDirec;
    public javax.swing.JTextField jTextNume;
    public javax.swing.JTextField jTextPreciTo;
    public javax.swing.JTextField jTextPreciUnit;
    public javax.swing.JTextField jTextTotal;
    public javax.swing.JPanel jpEscritorioF;
    public javax.swing.JTable miTb;
    public javax.swing.JTable miTb1;
    public rojeru_san.componentes.RSDateChooser rSDateFecha;
    // End of variables declaration//GEN-END:variables
}
